---
title: "Plots"
author: "Andrew Tredennick, Eric Marty"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(here)
library(ggpubr) # for multi plot figures

path <- here::here("output/current/")

allfiles <- list.files(path, ".csv")
allparfiles <- list.files(path, "params-natural.rds")
statedf <- readRDS(paste0(path,"statedf.rds"))
```

```{r plots, echo=FALSE, warning=FALSE, message = FALSE, fig.height = 9, out.width = "100%"}
for(i in 1:length(allfiles)) {
  f <- allfiles[i]
  parf <- allparfiles[i]
  fname <- paste0(path,f)
  parfname <- paste0(path,parf)
  statename <- gsub("\\.csv","",f)
  statepop <- statedf %>% dplyr::filter(state_full == statename) %>% pull(total_pop)

  # state parameters
  statepars <- readRDS(parfname) 

  statepars_fixed <- statepars %>% 
    rownames_to_column(var = "param") %>% 
    dplyr::filter(is_fitted == "no") %>% 
    select(param,X1) %>% 
    pivot_wider(values_from = X1, names_from = param) %>% 
    select(-c(MIF_ID, LogLik, LogLik_SE))

  statepars_fitted <- statepars %>% 
    rownames_to_column(var = "param") %>% 
    dplyr::filter(is_fitted == "yes") %>% 
    select(param,X1) %>% 
    pivot_wider(values_from = X1, names_from = param)
  
  statepars_allmle <- bind_cols(statepars_fixed,statepars_fitted)

  # state results
  stateresults <- read.csv(fname) %>% 
    mutate(date = as.Date(date)) 
  
  # calculate S
  stateresults <- stateresults %>% 
    filter(variable == "cumulative_all_infections") %>% 
    mutate(
      lower_80 = statepop - lower_80,
      lower_90 = statepop - lower_90,
      lower_95 = statepop - lower_95,
      mean_value = statepop - mean_value,
      median_value = statepop - median_value,
      upper_80 = statepop - upper_80,
      upper_90 = statepop - upper_90,
      upper_95 = statepop - upper_95
    ) %>% 
    mutate(variable = as.factor("S")) %>% 
    bind_rows(stateresults)


  # cases
  dat <- stateresults %>%
    filter(variable %in% c("actual_daily_cases"))
  stateresults %>%
    filter(variable %in% c("daily_cases")) %>%
    filter(sim_type == "status_quo") %>%
    filter(date <= (Sys.Date() + 7*4)) %>%
    ggplot(aes(x = date, y = median_value)) +
    geom_ribbon(aes(ymin = lower_80, ymax = upper_80), alpha = 0.2) +
    geom_line() +
    geom_line(data = dat, aes(x = date, y = mean_value), color = "blue") +
    ylab("daily cases") +
    ggtitle(statename) -> g_cases

  # deaths
  dat <- stateresults %>%
    filter(variable %in% c("actual_daily_deaths")) 
  stateresults %>%
    filter(variable %in% c("daily_deaths")) %>%
    filter(sim_type == "status_quo") %>%
    filter(date <= (Sys.Date() + 7*4)) %>%
    ggplot(aes(x = date, y = median_value)) +
    geom_ribbon(aes(ymin = lower_80, ymax = upper_80), alpha = 0.2) +
    geom_line() +
    ylab("daily deaths") +
    geom_line(data = dat, aes(x = date, y = mean_value), color = "blue") +
    ggtitle("") -> g_deaths

  # relative transmission, mobility, latent trend
  stateresults %>%
    filter(variable %in% c("combined_trend", "latent_trend", "mobility_trend")) %>%
    filter(sim_type == "status_quo") %>%
    ggplot(aes(x = date, y = mean_value)) +
    geom_point(aes(color = variable)) +
    ggtitle("") +
    xlab("") +
    theme(legend.position = "none") -> g_trends
  

  # death fraction
  daterange <- read_csv(fname) %>% pull(date) %>% range() %>% as.Date()
  date <- seq(daterange[1],daterange[2],1)
  t <- seq_along(date)
  min_frac_dead <- statepars['min_frac_dead','X1'] # minimum death fraction
  max_frac_dead <- statepars['max_frac_dead','X1'] # maximum death fraction
  log_half_dead <- statepars['log_half_dead','X1'] # time to 1/2 difference between min and max
  tibble(date = date, 
         death_fraction = max_frac_dead - (max_frac_dead - min_frac_dead) * (t / (t + log_half_dead))) %>% 
    ggplot(aes(x = date, y = death_fraction)) +
    geom_line() +
    geom_hline(yintercept=min_frac_dead, linetype="dashed") +
    geom_hline(yintercept=max_frac_dead, linetype="dashed") +
    geom_hline(yintercept=(max_frac_dead+min_frac_dead)/2,linetype="dashed") + 
    geom_vline(xintercept=daterange[1]+log_half_dead, linetype="dashed") +
    ggtitle("") +
    xlab("") +
    ylim(0,1) +
    theme(legend.position = "none") -> g_deathfrac

  figure <- ggarrange(g_cases, g_deaths, g_trends, g_deathfrac, ncol=1, nrow = 4, align="hv")
  cat(paste("--------------------------\n",statename,"\n"))
  
  parsf <- list.files(path, pattern=paste0("^",statename,".*","natural.rds"))
  parsdf <- readRDS(paste0(path,parsf))
  pars <- parsdf[,"X1"]
  names(pars) <- row.names(parsdf)
  display <- function(pars, parnames) {
    x <- pars[parnames]
    cat(paste(names(x), x, sep = ": ", collapse = "\n"))
  }
  display(pars, parnames=c('min_frac_dead',
                           'max_frac_dead',
                           'log_half_dead',
                           'theta_cases',
                           'theta_deaths',
                           'sigma_dw',
                           'E1_0','Ia1_0','Isu1_0','Isd1_0'))
  cat("\n")
  cat(paste("init R0:", statedf %>% filter(state_full == statename) %>% pull(initR0),"\n"))
  cat(paste("Warm start:", statedf %>% filter(state_full == statename) %>% pull(init),"\n"))
  cat(paste("MIF runs:", statedf %>% filter(state_full == statename) %>% pull(mifruns),"\n"))
  
  print(figure)

}



```




