---
title: "COVID-19 Model Fitting and Forecasting Report for U.S. States"
author: "Andrew Tredennick, Andreas Handel, and John Drake"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r libs}
library(pomp)
library(tidyverse)
library(here)
library(googlesheets4)
```


# Results

## In-Sample Trajectories

```{r us-traj}
all_files <- list.files(here("output"), pattern = "*.rds")
# if(length(all_files != 50)) stop("Too few or too many output files...")

for(do_file in all_files) {
  res <- readRDS(here("output", do_file))
  sim <- res$sims
  dat <- res$pomp_data
  
  print(do_file)
  
  sim %>%
    dplyr::select(time, cases) %>%
    group_by(time) %>%
    summarize(upper = quantile(cases, 0.9),
              ptval = ceiling(mean(cases)),
              lower = quantile(cases, 0.1)) %>%
    ggplot(aes(x = time, y = ptval)) +
    geom_line() +
    geom_line(aes(y = upper), linetype = 2) +
    geom_line(aes(y = lower), linetype = 2) +
    geom_line(data = dat, aes(x = time, y = cases), color = "red") +
    ggtitle("Cases") -> g1
  
  sim %>%
    dplyr::select(time, D_new) %>%
    rename("deaths" = D_new) %>%
    group_by(time) %>%
    summarize(upper = quantile(deaths, 0.9),
              ptval = ceiling(mean(deaths)),
              lower = quantile(deaths, 0.1)) %>%
    ggplot(aes(x = time, y = ptval)) +
    geom_line() +
    geom_line(aes(y = upper), linetype = 2) +
    geom_line(aes(y = lower), linetype = 2) +
    geom_line(data = dat, aes(x = time, y = deaths), color = "red") +
    ggtitle("Deaths") -> g2
  
  sim %>%
    dplyr::select(time, trendO) %>%
    filter(time > 1) %>%
    group_by(time) %>%
    summarize(ptval = mean(exp(trendO)/(1+exp(trendO)))) %>%
    ggplot(aes(x = time, y = ptval)) +
    geom_line() +
    ylim(c(0, 1)) +
    ggtitle("Latent trend") -> g3

# dates <- unique(dat$date)
# num_days <- length(dates)
# n_knots <- round(num_days / 10)
# bases <- pomp::bspline.basis(x=1:num_days, nbasis=n_knots, degree=3)
# 
# res$partable %>%
#   slice(1) %>%
#   mutate(id = 1:n()) %>%
#   gather("key", "value", -id) %>%
#   filter(key %in% paste0("b", 1:n_knots)) %>%
#   dplyr::select(-id) %>%
#   deframe() -> betas
# 
# 
# trend <- bases %*% betas
# trend <- exp(trend) / (1+exp(trend))
# trend_df <- tibble(
#   Date = dates,
#   Psi = trend,
#   Phi = covar$rel_beta_change) %>%
#   mutate(PhiPsi = Phi*Psi) %>%
#   gather("key", "value", -Date)
# 
# ggplot(trend_df, aes(Date, value, color = key)) +
#   geom_line(aes(size = key)) +
#   scale_y_continuous(limits = c(0, 1)) +
#   scale_color_manual(values = c("dodgerblue", "black", "salmon")) +
#   scale_size_manual(values = c(1,2,1)) +
#   theme_minimal(base_size = 14, base_line_size = 0.5) +
#   theme(legend.position = "top") -> phipsi
# 
# beta_trend <- trend_df %>%
#   filter(key == "PhiPsi") %>%
#   mutate(beta = value * beta_est)
# 
# ggplot(beta_trend, aes(x = Date, y = beta)) +
#   geom_line() +
#   ylab(expression(beta[t]))+
#   theme_minimal(base_size = 14, base_line_size = 0.5) -> btrend
  
  gout <- cowplot::plot_grid(g1, g2, g3, ncol = 1)
  print(gout)
}
``` 

## Projections

```{r sqs}
all_files <- list.files(here("output"), pattern = "*.rds")
# if(length(all_files != 50)) stop("Too few or too many output files...")

for(do_file in all_files) {
  res <- readRDS(here("output", do_file))
  sims <- res$scenarios$sims
  sim_summs <- sims %>%
  dplyr::select(SimType, Period, Date, cases, deaths) %>%
  rename("Acases" = cases,
         "Cdeaths" = deaths) %>%
  gather(key = "Variable", value = "Value", -SimType, -Period, -Date) %>%
  group_by(SimType, Period, Date, Variable) %>%
  summarise(lower = ceiling(quantile(Value, 0.025)),
            ptvalue = ceiling(mean(Value)),
            # ptvalue = median(Value),
            upper = ceiling(quantile(Value, 0.975))) %>%
  ungroup() %>%
    mutate(lower = ifelse(Period == "Past", ptvalue, lower),
           upper = ifelse(Period == "Past", ptvalue, upper))
  
  res$pomp_data %>%
    dplyr::select(date, cases, deaths) %>%
    rename("Acases" = cases,
           "Cdeaths" = deaths,
           "Date" = date) %>%
    gather(key = "Variable", value = "Value", -Date) %>%
    mutate(SimType = "status_quo") -> dat
  datAll <- dat %>%
    bind_rows(dat %>% mutate(SimType = "linear_increase_sd")) %>%
    bind_rows(dat %>% mutate(SimType = "return_normal"))
  
  ggplot(sim_summs, aes(x = Date, y = ptvalue)) +
    geom_line() +
    geom_line(data = datAll, aes(x = Date, y = Value), col = "red") +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) +
    facet_wrap(SimType ~ Variable,scales = "free", ncol = 2) -> simout
  print(do_file)
  print(simout)

}
```

## Parameter Estimates
```{r params, results='asis', eval = TRUE}
all_files <- list.files(here("output"), pattern = "*.rds")
# if(length(all_files != 50)) stop("Too few or too many output files...")
betas <- tibble()
for(do_file in all_files) {
  res <- readRDS(here("output", do_file))
  mindate <- min(res$pomp_data$date)
  partab <- res$partable_natural
  param_names <- rownames(partab)
  pop <- res$all_partable$S_0[1]
  print(res$location)
  cat("\n")
  res$partable_natural %>%
    mutate(Names = param_names) %>%
    filter(is_fitted == "yes") %>%
    dplyr::select(X1, Names) %>%
    mutate(X1 = ifelse(Names == "beta_s", X1 * pop, X1)) %>%
    rename("MLE" = X1) -> tab
  tab %>%
    knitr::kable() %>%
    print()
  cat("\n")
  betas <- betas %>%
    bind_rows(tibble(beta = tab %>% filter(Names == "beta_s") %>% pull(MLE),
                     location = res$location))
}
```

## Baseline transmission rate parameters

```{r histo}
ggplot(data = betas, aes(x = location, y = beta)) +
  geom_col(fill = "dodgerblue") +
  coord_flip()
```
